Name:           perl-Log-Any-Adapter-Log4perl
Version:        0.08
Release:        1%{?dist}
Summary:        Log::Any adapter for Log::Log4perl
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Log-Any-Adapter-Log4perl/
Source0:        http://www.cpan.org/authors/id/D/DA/DAGOLDEN/Log-Any-Adapter-Log4perl-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(File::Temp) >= 0.20
BuildRequires:  perl(Log::Any::Adapter) >= 1.03
BuildRequires:  perl(Log::Any::Adapter::Base)
BuildRequires:  perl(Log::Any::Adapter::Util) >= 1.03
BuildRequires:  perl(Log::Log4perl) >= 1.32
BuildRequires:  perl(strict)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(warnings)
Requires:       perl(Log::Any::Adapter::Base)
Requires:       perl(Log::Any::Adapter::Util) >= 1.03
Requires:       perl(Log::Log4perl) >= 1.32
Requires:       perl(strict)
Requires:       perl(warnings)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This Log::Any adapter uses Log::Log4perl for logging. log4perl must be
initialized before calling set. There are no parameters.

%prep
%setup -q -n Log-Any-Adapter-Log4perl-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes CONTRIBUTING.mkdn cpanfile dist.ini LICENSE META.json perlcritic.rc README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Jun 09 2016 Nicholas van Oudtshoorn <vanoudt@gmail.com> 0.08-1
- Specfile autogenerated by cpanspec 1.78.
